src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modified_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Product", mappedBy="category")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeInterface
    {
        return $this->modified_at;
    }

    public function setModifiedAt(\DateTimeInterface $modified_at): self
    {
        $this->modified_at = $modified_at;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Categorienaam'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Product;
use App\Form\CategoryType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CategoryController extends AbstractController
{
    /**
     * @Route("/admin/category", name="admin_category_index")
     */
    public function index() {
        $em = $this->getDoctrine()->getManager();

        $categories = $em->getRepository(Category::class)->findAll();

        return $this->render('category/index.html.twig', [
            'title' => 'Categoriën',
            'categories' => $categories,
        ]);
    }

    /**
     * @Route("/admin/function/categoryform/{id}", name="admin_function_categoryform")
     */
    public function getCategoryForm($id = 0) {
        $em = $this->getDoctrine()->getManager();

        $category = $id === 0 ? new Category() : $em->getRepository(Category::class)->find($id);
        $actionId = $id === 0 ? null : $id;

        $form = $this->createForm(CategoryType::class, $category, [
            'action' => $this->generateUrl('admin_function_categoryformaction', [
                'id' => $actionId,
            ]),
        ]);

        $html = $this->renderView('sections/categoryform.html.twig', [
            'form' => $form->createView(),
        ]);

        return new JsonResponse($html);
    }

    /**
     * @Route("/admin/function/categoryformaction/{id}", name="admin_function_categoryformaction")
     */
    public function categoryFormAction(Request $request, $id = 0) {
        $em = $this->getDoctrine()->getManager();
        $data = $request->request->get('category');

        $category = $id === 0 ? new Category() : $em->getRepository(Category::class)->find($id);

        $category->setName($data['name']);
        $category->setCreatedAt(new \DateTime('now'));
        if ($id !== 0 ) { $category->setModifiedAt(new \DateTime('now'));}

        $em->persist($category);
        $em->flush();

        $this->addFlash('success', 'Categorie actie succesvol!');
        $referer = $request->headers->get('referer');
        return new RedirectResponse($referer);
    }

    /**
     * @Route("/admin/function/deletecategory/{id}", name="admin_function_deletecategory")
     */
    public function deleteProduct(Request $request, $id) {
        $em = $this->getDoctrine()->getManager();

        $category = $em->getRepository(Category::class)->find($id);

        if ($category === null) {
            $this->addFlash('danger', 'Categorie niet gevonden!');
        } else {
            $em->remove($category);
            $em->flush();
            $this->addFlash('success', 'Categorie succesvol verwijderd!');
        }

        $referer = $request->headers->get('referer');
        return new RedirectResponse($referer);
    }
}

templates/category/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.20/datatables.min.css"/>
{% endblock %}

{% block body %}
    <h2>Categoriënoverzicht</h2>
    <hr>
    <div class="row">
        <div class="col-lg-12">
            <button class="btn btn-success float-right mb-4 category_action_category_button" data-action="add" data-id="0"><i class="fa fa-plus"></i> Toevoegen</button>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-sm table-hover table-responsive-md" id="product_table">
                <tr>
                    <th>Naam</th>
                    <th>Aangemaakt op</th> 
                    <th>Laatst bewerkt op</th>
                    <th>Acties</th>
                </tr>
                {% for category in categories  %}
                    <tr>
                        <td>{{ category.name }}</td>
                        <td>{{ category.createdAt|date('d-m-Y') }}</td>
                        <td>{{ category.modifiedAt|date('d-m-Y') }}</td>
                        <td>
                            <button type="button" data-action="update" data-id="{{ category.id }}" class="btn btn-sm btn-warning category_action_category_button"><i class="fa fa-pencil"></i> Bewerken</button>
                            <a href="{{ path('admin_function_deletecategory', {id : category.id}) }}" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Verwijderen</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="category-modal modal fade" id="category-modal" tabindex="-1" role="dialog" aria-labelledby="category-modalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="category-modalLabel">Categorie</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Afsluiten</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/datatables.min.js"></script>
{% endblock %}